// Auto-generated scene image pools.
// Source: public/images/generated/<theme>/*
// Generated by: scripts/build-generated-scene-images.mjs
export const GENERATED_SCENE_IMAGE_POOLS: Record<string, string[]> = {
};
