// Auto-generated scene image pools.
// Source: public/images/generated/<theme>/*
// Generated by: scripts/build-generated-scene-images.mjs
export const GENERATED_SCENE_IMAGE_POOLS: Record<string, string[]> = {
  "adventure": [
    "/images/generated/adventure/adventure-001.svg",
    "/images/generated/adventure/adventure-002.svg",
    "/images/generated/adventure/adventure-003.svg",
  ],
  "calm": [
    "/images/generated/calm/calm-001.svg",
    "/images/generated/calm/calm-002.svg",
    "/images/generated/calm/calm-003.svg",
  ],
  "magic": [
    "/images/generated/magic/magic-001.svg",
    "/images/generated/magic/magic-002.svg",
    "/images/generated/magic/magic-003.svg",
  ],
};
